sudo: required
services:
    - docker
    
before_install:
    - docker build -t josearivas/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true josearivas/docker-react npm run test     
