sudo: required
services:
    - docker
    
before_install:
    - docker build -t josearivas/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true josearivas/docker-react npm run test     

notifications:
    email:
        recipients:
            - rivass.josea@gmail.com
        on_success: always
        on_failure: always

# AWS Elastic Beanstalk        
#deploy:
#    provider: elasticbeanstalk
#    region: "us-west-2"
#    app: "docker"
#    env: "Docker-env"
#    bucket-name: "elasticbeanstalk-us-west-2-306476627547"
#    bucker-path: "docker"
#    on:
#        branch: master        
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#        secure: "$AWS_SECRET_KEY"
        
# Custom deployment        
#deploy:
#    provider: script
#    script: bash scripts/deploy.sh
#    on:
#        branch: master        
